[2023-07-24 12:07:21,028] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_dag.move_data_to_another_table manual__2023-07-24T12:06:52.754383+00:00 [queued]>
[2023-07-24 12:07:21,102] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_dag.move_data_to_another_table manual__2023-07-24T12:06:52.754383+00:00 [queued]>
[2023-07-24 12:07:21,115] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 12:07:21,117] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-24 12:07:21,119] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 12:07:21,245] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): move_data_to_another_table> on 2023-07-24 12:06:52.754383+00:00
[2023-07-24 12:07:21,278] {standard_task_runner.py:52} INFO - Started process 4666 to run task
[2023-07-24 12:07:21,357] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'move_data_to_another_table', 'manual__2023-07-24T12:06:52.754383+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpn2nn6skn', '--error-file', '/tmp/tmpdvjtj2ku']
[2023-07-24 12:07:21,362] {standard_task_runner.py:80} INFO - Job 71: Subtask move_data_to_another_table
[2023-07-24 12:07:21,715] {task_command.py:370} INFO - Running <TaskInstance: etl_dag.move_data_to_another_table manual__2023-07-24T12:06:52.754383+00:00 [running]> on host c03236539c84
[2023-07-24 12:07:21,995] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=move_data_to_another_table
AIRFLOW_CTX_EXECUTION_DATE=2023-07-24T12:06:52.754383+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-24T12:06:52.754383+00:00
[2023-07-24 12:07:22,034] {base.py:68} INFO - Using connection ID 'postgres://cazwrmravtstuq:***@ec2-54-234-13-16.compute-1.amazonaws.com:5432/d7ojfso4s2fmat' for task execution.
[2023-07-24 12:07:22,641] {dbapi.py:213} INFO - Running statement: INSERT INTO public.fraudtest_new (trans_date_trans_time, cc_num, merchant, category, amt, first, last, gender, street, city, state, zip, lat, long, city_pop, job, dob, trans_num, unix_time, merch_lat, merch_long, is_fraud, prediction) SELECT trans_date_trans_time, cc_num, merchant, category, amt, first, last, gender, street, city, state, zip, lat, long, city_pop, job, dob, trans_num, unix_time, merch_lat, merch_long, is_fraud, prediction FROM real_time_data;, parameters: None
[2023-07-24 12:07:22,820] {dbapi.py:221} INFO - Rows affected: 5
[2023-07-24 12:07:23,077] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=move_data_to_another_table, execution_date=20230724T120652, start_date=20230724T120721, end_date=20230724T120723
[2023-07-24 12:07:23,196] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-07-24 12:07:23,357] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
