[2023-07-24 10:07:18,079] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_dag.transfer_data_to_postgres scheduled__2023-07-24T09:00:00+00:00 [queued]>
[2023-07-24 10:07:18,246] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_dag.transfer_data_to_postgres scheduled__2023-07-24T09:00:00+00:00 [queued]>
[2023-07-24 10:07:18,252] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 10:07:18,257] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-24 10:07:18,264] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 10:07:18,449] {taskinstance.py:1377} INFO - Executing <Task(S3ToPostgresOperator): transfer_data_to_postgres> on 2023-07-24 09:00:00+00:00
[2023-07-24 10:07:18,470] {standard_task_runner.py:52} INFO - Started process 776 to run task
[2023-07-24 10:07:18,506] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'transfer_data_to_postgres', 'scheduled__2023-07-24T09:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmphysy_gxt', '--error-file', '/tmp/tmp696aoqpv']
[2023-07-24 10:07:18,513] {standard_task_runner.py:80} INFO - Job 22: Subtask transfer_data_to_postgres
[2023-07-24 10:07:18,854] {task_command.py:370} INFO - Running <TaskInstance: etl_dag.transfer_data_to_postgres scheduled__2023-07-24T09:00:00+00:00 [running]> on host c03236539c84
[2023-07-24 10:07:19,837] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=transfer_data_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-07-24T09:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-24T09:00:00+00:00
[2023-07-24 10:07:19,854] {s3.py:861} INFO - Downloading source S3 file from Bucket lead-project-bucket-ojo with path Real_time_payments_update
[2023-07-24 10:07:20,082] {base.py:68} INFO - Using connection ID 'aws_default' for task execution.
[2023-07-24 10:07:20,101] {base_aws.py:206} INFO - Credentials retrieved from login
[2023-07-24 10:07:22,417] {base.py:68} INFO - Using connection ID 'postgres://cazwrmravtstuq:***@ec2-54-234-13-16.compute-1.amazonaws.com:5432/d7ojfso4s2fmat' for task execution.
[2023-07-24 10:07:24,691] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=transfer_data_to_postgres, execution_date=20230724T090000, start_date=20230724T100718, end_date=20230724T100724
[2023-07-24 10:07:24,807] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-07-24 10:07:24,913] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-24 10:28:20,814] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_dag.transfer_data_to_postgres scheduled__2023-07-24T09:00:00+00:00 [queued]>
[2023-07-24 10:28:20,896] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_dag.transfer_data_to_postgres scheduled__2023-07-24T09:00:00+00:00 [queued]>
[2023-07-24 10:28:20,903] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 10:28:20,904] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-24 10:28:20,904] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 10:28:21,077] {taskinstance.py:1377} INFO - Executing <Task(S3ToPostgresOperator): transfer_data_to_postgres> on 2023-07-24 09:00:00+00:00
[2023-07-24 10:28:21,124] {standard_task_runner.py:52} INFO - Started process 1466 to run task
[2023-07-24 10:28:21,190] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'transfer_data_to_postgres', 'scheduled__2023-07-24T09:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpycv0cxk3', '--error-file', '/tmp/tmp5ri5itoc']
[2023-07-24 10:28:21,206] {standard_task_runner.py:80} INFO - Job 32: Subtask transfer_data_to_postgres
[2023-07-24 10:28:21,688] {task_command.py:370} INFO - Running <TaskInstance: etl_dag.transfer_data_to_postgres scheduled__2023-07-24T09:00:00+00:00 [running]> on host c03236539c84
[2023-07-24 10:28:22,239] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=transfer_data_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-07-24T09:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-24T09:00:00+00:00
[2023-07-24 10:28:22,249] {s3.py:861} INFO - Downloading source S3 file from Bucket lead-project-bucket-ojo with path Real_time_payments_1690187507.8259003.csv
[2023-07-24 10:28:22,290] {base.py:68} INFO - Using connection ID 'aws_default' for task execution.
[2023-07-24 10:28:22,293] {base_aws.py:206} INFO - Credentials retrieved from login
[2023-07-24 10:28:23,685] {base.py:68} INFO - Using connection ID 'postgres://cazwrmravtstuq:***@ec2-54-234-13-16.compute-1.amazonaws.com:5432/d7ojfso4s2fmat' for task execution.
[2023-07-24 10:28:25,628] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1686, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 909, in do_executemany
    **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1270, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "cc_num" of relation "public.fraudtest_new" does not exist
LINE 1: INSERT INTO "public.fraudtest_new" (cc_num, merchant, catego...
                                            ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/airflow/plugins/s3toPostgres.py", line 42, in execute
    df_file.to_sql(self.table, engine, if_exists="append", index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 728, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1770, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1350, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1340, in insert_records
    table.insert(chunksize=chunksize, method=method)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 967, in insert
    exec_insert(conn, keys, chunk_iter)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 882, in _execute_insert
    conn.execute(self.table.insert(), data)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 314, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1399, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1686, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 909, in do_executemany
    **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1270, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "cc_num" of relation "public.fraudtest_new" does not exist
LINE 1: INSERT INTO "public.fraudtest_new" (cc_num, merchant, catego...
                                            ^

[SQL: INSERT INTO "public.fraudtest_new" (cc_num, merchant, category, amt, first, last, gender, street, city, state, zip, lat, long, city_pop, job, dob, trans_num, merch_lat, merch_long, is_fraud, "current_time", trans_date_trans_time, unix_time, prediction) VALUES (%(cc_num)s, %(merchant)s, %(category)s, %(amt)s, %(first)s, %(last)s, %(gender)s, %(street)s, %(city)s, %(state)s, %(zip)s, %(lat)s, %(long)s, %(city_pop)s, %(job)s, %(dob)s, %(trans_num)s, %(merch_lat)s, %(merch_long)s, %(is_fraud)s, %(current_time)s, %(trans_date_trans_time)s, %(unix_time)s, %(prediction)s)]
[parameters: ({'cc_num': 3549202406645667, 'merchant': 'fraud_Larson, Quitzon and Spencer', 'category': 'travel', 'amt': 5.95, 'first': 'Larry', 'last': 'Williams', 'gender': 'M', 'street': '6274 David Oval Suite 725', 'city': 'Scarborough', 'state': 'ME', 'zip': 4074, 'lat': 43.5835, 'long': -70.3457, 'city_pop': 18760, 'job': 'Make', 'dob': '1933-04-02', 'trans_num': '432b6a4a5058924105e2ec1f5bcfdfb8', 'merch_lat': 44.467539, 'merch_long': -69.491607, 'is_fraud': 0, 'current_time': 1690187012053, 'trans_date_trans_time': '2023-07-24 08:23:32', 'unix_time': 1690187012, 'prediction': 1}, {'cc_num': 4512828414983801773, 'merchant': 'fraud_Heller-Langosh', 'category': 'gas_transport', 'amt': 44.55, 'first': 'Monica', 'last': 'Cohen', 'gender': 'F', 'street': '864 Reynolds Plains', 'city': 'Uledi', 'state': 'PA', 'zip': 15484, 'lat': 39.8936, 'long': -79.7856, 'city_pop': 328, 'job': 'Tree surgeon', 'dob': '1983-07-25', 'trans_num': 'a3a7f6b7a6ea8411e53604f8015b9f04', 'merch_lat': 38.966845, 'merch_long': -79.933747, 'is_fraud': 0, 'current_time': 1690187030599, 'trans_date_trans_time': '2023-07-24 08:23:50', 'unix_time': 1690187030, 'prediction': 1}, {'cc_num': 3519607465576254, 'merchant': 'fraud_Jenkins, Hauck and Friesen', 'category': 'gas_transport', 'amt': 61.46, 'first': 'Audrey', 'last': 'Gonzalez', 'gender': 'F', 'street': '34180 Lopez Plaza', 'city': 'Fields Landing', 'state': 'CA', 'zip': 95537, 'lat': 40.7268, 'long': -124.2174, 'city_pop': 276, 'job': 'Scientist, audiological', 'dob': '1929-05-06', 'trans_num': '6ed849745dd885095dfcfdcfed87e195', 'merch_lat': 41.100195, 'merch_long': -124.416337, 'is_fraud': 0, 'current_time': 1690187048367, 'trans_date_trans_time': '2023-07-24 08:24:08', 'unix_time': 1690187048, 'prediction': 1}, {'cc_num': 4377338765909719, 'merchant': 'fraud_Roberts-Beahan', 'category': 'misc_pos', 'amt': 1.09, 'first': 'Nicholas', 'last': 'Mcmahon', 'gender': 'M', 'street': '2123 Jonathan Falls Suite 753', 'city': 'Heiskell', 'state': 'TN', 'zip': 37754, 'lat': 36.115, 'long': -84.0438, 'city_pop': 4729, 'job': 'Geologist, wellsite', 'dob': '1982-04-19', 'trans_num': '580f06bb1228b3aa812d414582c788bc', 'merch_lat': 36.714936, 'merch_long': -84.904307, 'is_fraud': 0, 'current_time': 1690187066092, 'trans_date_trans_time': '2023-07-24 08:24:26', 'unix_time': 1690187066, 'prediction': 1}, {'cc_num': 378904938837132, 'merchant': 'fraud_Smitham-Boehm', 'category': 'grocery_net', 'amt': 52.48, 'first': 'Tina', 'last': 'Zimmerman', 'gender': 'F', 'street': '3595 Susan Island Suite 063', 'city': 'Thomas', 'state': 'OK', 'zip': 73669, 'lat': 35.7382, 'long': -98.7388, 'city_pop': 1675, 'job': 'Barrister', 'dob': '1986-05-01', 'trans_num': '4092c01a93496a42ed49e12f54f55f4d', 'merch_lat': 35.879473, 'merch_long': -99.381656, 'is_fraud': 0, 'current_time': 1690187083685, 'trans_date_trans_time': '2023-07-24 08:24:43', 'unix_time': 1690187083, 'prediction': 1})]
(Background on this error at: http://sqlalche.me/e/14/f405)
[2023-07-24 10:28:25,711] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=transfer_data_to_postgres, execution_date=20230724T090000, start_date=20230724T102820, end_date=20230724T102825
[2023-07-24 10:28:25,764] {standard_task_runner.py:97} ERROR - Failed to execute job 32 for task transfer_data_to_postgres ((psycopg2.errors.UndefinedColumn) column "cc_num" of relation "public.fraudtest_new" does not exist
LINE 1: INSERT INTO "public.fraudtest_new" (cc_num, merchant, catego...
                                            ^

[SQL: INSERT INTO "public.fraudtest_new" (cc_num, merchant, category, amt, first, last, gender, street, city, state, zip, lat, long, city_pop, job, dob, trans_num, merch_lat, merch_long, is_fraud, "current_time", trans_date_trans_time, unix_time, prediction) VALUES (%(cc_num)s, %(merchant)s, %(category)s, %(amt)s, %(first)s, %(last)s, %(gender)s, %(street)s, %(city)s, %(state)s, %(zip)s, %(lat)s, %(long)s, %(city_pop)s, %(job)s, %(dob)s, %(trans_num)s, %(merch_lat)s, %(merch_long)s, %(is_fraud)s, %(current_time)s, %(trans_date_trans_time)s, %(unix_time)s, %(prediction)s)]
[parameters: ({'cc_num': 3549202406645667, 'merchant': 'fraud_Larson, Quitzon and Spencer', 'category': 'travel', 'amt': 5.95, 'first': 'Larry', 'last': 'Williams', 'gender': 'M', 'street': '6274 David Oval Suite 725', 'city': 'Scarborough', 'state': 'ME', 'zip': 4074, 'lat': 43.5835, 'long': -70.3457, 'city_pop': 18760, 'job': 'Make', 'dob': '1933-04-02', 'trans_num': '432b6a4a5058924105e2ec1f5bcfdfb8', 'merch_lat': 44.467539, 'merch_long': -69.491607, 'is_fraud': 0, 'current_time': 1690187012053, 'trans_date_trans_time': '2023-07-24 08:23:32', 'unix_time': 1690187012, 'prediction': 1}, {'cc_num': 4512828414983801773, 'merchant': 'fraud_Heller-Langosh', 'category': 'gas_transport', 'amt': 44.55, 'first': 'Monica', 'last': 'Cohen', 'gender': 'F', 'street': '864 Reynolds Plains', 'city': 'Uledi', 'state': 'PA', 'zip': 15484, 'lat': 39.8936, 'long': -79.7856, 'city_pop': 328, 'job': 'Tree surgeon', 'dob': '1983-07-25', 'trans_num': 'a3a7f6b7a6ea8411e53604f8015b9f04', 'merch_lat': 38.966845, 'merch_long': -79.933747, 'is_fraud': 0, 'current_time': 1690187030599, 'trans_date_trans_time': '2023-07-24 08:23:50', 'unix_time': 1690187030, 'prediction': 1}, {'cc_num': 3519607465576254, 'merchant': 'fraud_Jenkins, Hauck and Friesen', 'category': 'gas_transport', 'amt': 61.46, 'first': 'Audrey', 'last': 'Gonzalez', 'gender': 'F', 'street': '34180 Lopez Plaza', 'city': 'Fields Landing', 'state': 'CA', 'zip': 95537, 'lat': 40.7268, 'long': -124.2174, 'city_pop': 276, 'job': 'Scientist, audiological', 'dob': '1929-05-06', 'trans_num': '6ed849745dd885095dfcfdcfed87e195', 'merch_lat': 41.100195, 'merch_long': -124.416337, 'is_fraud': 0, 'current_time': 1690187048367, 'trans_date_trans_time': '2023-07-24 08:24:08', 'unix_time': 1690187048, 'prediction': 1}, {'cc_num': 4377338765909719, 'merchant': 'fraud_Roberts-Beahan', 'category': 'misc_pos', 'amt': 1.09, 'first': 'Nicholas', 'last': 'Mcmahon', 'gender': 'M', 'street': '2123 Jonathan Falls Suite 753', 'city': 'Heiskell', 'state': 'TN', 'zip': 37754, 'lat': 36.115, 'long': -84.0438, 'city_pop': 4729, 'job': 'Geologist, wellsite', 'dob': '1982-04-19', 'trans_num': '580f06bb1228b3aa812d414582c788bc', 'merch_lat': 36.714936, 'merch_long': -84.904307, 'is_fraud': 0, 'current_time': 1690187066092, 'trans_date_trans_time': '2023-07-24 08:24:26', 'unix_time': 1690187066, 'prediction': 1}, {'cc_num': 378904938837132, 'merchant': 'fraud_Smitham-Boehm', 'category': 'grocery_net', 'amt': 52.48, 'first': 'Tina', 'last': 'Zimmerman', 'gender': 'F', 'street': '3595 Susan Island Suite 063', 'city': 'Thomas', 'state': 'OK', 'zip': 73669, 'lat': 35.7382, 'long': -98.7388, 'city_pop': 1675, 'job': 'Barrister', 'dob': '1986-05-01', 'trans_num': '4092c01a93496a42ed49e12f54f55f4d', 'merch_lat': 35.879473, 'merch_long': -99.381656, 'is_fraud': 0, 'current_time': 1690187083685, 'trans_date_trans_time': '2023-07-24 08:24:43', 'unix_time': 1690187083, 'prediction': 1})]
(Background on this error at: http://sqlalche.me/e/14/f405); 1466)
[2023-07-24 10:28:25,827] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-24 10:28:25,951] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-24 10:28:26,046] {dagrun.py:547} ERROR - Marking run <DagRun etl_dag @ 2023-07-24 09:00:00+00:00: scheduled__2023-07-24T09:00:00+00:00, externally triggered: False> failed
[2023-07-24 10:28:26,050] {dagrun.py:622} INFO - DagRun Finished: dag_id=etl_dag, execution_date=2023-07-24 09:00:00+00:00, run_id=scheduled__2023-07-24T09:00:00+00:00, run_start_date=2023-07-24 10:28:00.651677+00:00, run_end_date=2023-07-24 10:28:26.048269+00:00, run_duration=25.396592, state=failed, external_trigger=False, run_type=scheduled, data_interval_start=2023-07-24 09:00:00+00:00, data_interval_end=2023-07-24 10:00:00+00:00, dag_hash=3da84dd1b5b336aef165512245280e19
