[2023-07-24 13:05:34,032] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_dag.move_data_to_another_table manual__2023-07-24T13:04:35.626713+00:00 [queued]>
[2023-07-24 13:05:34,095] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_dag.move_data_to_another_table manual__2023-07-24T13:04:35.626713+00:00 [queued]>
[2023-07-24 13:05:34,096] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 13:05:34,096] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-24 13:05:34,097] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 13:05:34,197] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): move_data_to_another_table> on 2023-07-24 13:04:35.626713+00:00
[2023-07-24 13:05:34,215] {standard_task_runner.py:52} INFO - Started process 256 to run task
[2023-07-24 13:05:34,233] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'move_data_to_another_table', 'manual__2023-07-24T13:04:35.626713+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpyv6yo57m', '--error-file', '/tmp/tmp51lymx3s']
[2023-07-24 13:05:34,238] {standard_task_runner.py:80} INFO - Job 104: Subtask move_data_to_another_table
[2023-07-24 13:05:34,415] {task_command.py:370} INFO - Running <TaskInstance: etl_dag.move_data_to_another_table manual__2023-07-24T13:04:35.626713+00:00 [running]> on host 58d73bc824ec
[2023-07-24 13:05:34,632] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=move_data_to_another_table
AIRFLOW_CTX_EXECUTION_DATE=2023-07-24T13:04:35.626713+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-24T13:04:35.626713+00:00
[2023-07-24 13:05:34,675] {base.py:68} INFO - Using connection ID 'postgres://cazwrmravtstuq:***@ec2-54-234-13-16.compute-1.amazonaws.com:5432/d7ojfso4s2fmat' for task execution.
[2023-07-24 13:05:35,245] {dbapi.py:213} INFO - Running statement: INSERT INTO public.fraudtest_new (trans_date_trans_time, cc_num, merchant, category, amt, first, last, gender, street, city, state, zip, lat, long, city_pop, job, dob, trans_num, unix_time, merch_lat, merch_long, is_fraud, prediction) SELECT trans_date_trans_time, cc_num, merchant, category, amt, first, last, gender, street, city, state, zip, lat, long, city_pop, job, dob, trans_num, unix_time, merch_lat, merch_long, is_fraud, prediction FROM real_time_data;, parameters: None
[2023-07-24 13:05:35,427] {dbapi.py:221} INFO - Rows affected: 5
[2023-07-24 13:05:35,542] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=move_data_to_another_table, execution_date=20230724T130435, start_date=20230724T130534, end_date=20230724T130535
[2023-07-24 13:05:35,592] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-07-24 13:05:35,701] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
